packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  typescript: ^5.7.3
  zod: ^3.25.49
  "@phosphor-icons/react": "^2.1.10"

catalogs:
  react19:
    react: ^19.0.0
    "react-dom": ^19.0.0
    "@types/node": "^20"
    "@types/react": "^19"
    "@types/react-dom": "^19"
